### PR TITLE
Add sourcehut builds

### PR DESCRIPTION
**Pull request by chrisduerr**

### CODE REVIEW

**Comment by kchibisov** [comment]
Since urlocator is generic and doesn't contain any platform specific code, may we just remove CI on anything other than Linux?

**Comment by chrisduerr** [comment]
> Since urlocator is generic and doesn't contain any platform specific code, may we just remove CI on anything other than Linux?

Sounds like a good idea, should we go for only sourcehut then?

**Comment by kchibisov** [comment]
You should add clippy as well.

**Comment by chrisduerr** [comment]
> You should add clippy as well.

It already is added.

**Review by kchibisov — APPROVED** [review]

**Review by kchibisov — CHANGES_REQUESTED** [review]
Oh, actually, could we ensure that https://github.com/alacritty/vte/pull/61 won't happen here? I'm not sure why `vte` failed, but `urlocator` passed here without that error?

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
